src/backend/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/chat/urls.py
from django.urls import path
from .views import ConversationCreateView, ConversationListView, MessageListView, ThoughtListView

app_name = "chat"
urlpatterns = [
    path("", ConversationListView.as_view(), name="conversations"),
    path("create_conversation/", ConversationCreateView.as_view(), name="create_conversation"),
    path("<int:id>/", MessageListView.as_view(), name="messages"),
    path("msg/<int:id>/", ThoughtListView.as_view(), name="thoughts"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

src/chat/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from django.utils import timezone


class ConversationModel(models.Model):
    title = models.CharField(max_length=280, unique=True, blank=False)
    description = models.TextField(null=True, blank=True)
    date = models.DateField(default=date.today)

    def get_absolute_url(self):
        return reverse("chat:messages", kwargs={"id": self.id})


class MessageModel(models.Model):
    conversation_id = models.ForeignKey(ConversationModel, on_delete=models.CASCADE)
    content = models.TextField(null=False, blank=False)
    date_time = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("chat:thoughts", kwargs={"id": self.id})


class ThoughtModel(models.Model):
    message_id = models.ForeignKey(MessageModel, on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=False)
    date_time = models.DateTimeField(default=timezone.now)

src/chat/forms.py
from django import forms

from .models import ConversationModel


class ConversationCreateForm(forms.ModelForm):
    class Meta:
        model = ConversationModel
        fields = ["title", "description", "date"]

src/chat/views.py
from django.http import Http404
from django.urls import reverse
from django.views.generic import CreateView, ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db.models import F, Count

from .models import ConversationModel, MessageModel, ThoughtModel
from .forms import ConversationCreateForm


class ConversationListView(ListView):
    template_name = "conversation_list.html"
    queryset = ConversationModel.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        query = self.request.GET.get("q", "")
        vector = SearchVector("title")
        search_query = SearchQuery(query)
        object_list = (ConversationModel.objects.filter(title__icontains=query).annotate(
            rank=SearchRank(vector, search_query), content=F("title"), date_time=F("date"),
            sub_content_count=Count('messagemodel')).order_by("-rank"))

        context.update({
            "object_list": object_list,
            "has_search": True,
            "menu_title": "Conversations",
            "prev_page": None,
        })
        return context


class ConversationCreateView(CreateView):
    template_name = "conversation_create.html"
    form_class = ConversationCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "menu_title": "Messages",
            "prev_page": reverse("chat:conversations"),
        })
        return context


class MessageListView(CreateView):
    template_name = "messages.html"
    model = MessageModel
    fields = ["content", "date_time"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        conv_id = self.kwargs.get("id")
        try:
            context["conversation"] = ConversationModel.objects.get(id=conv_id)
        except ConversationModel.DoesNotExist:
            raise Http404("Conversation does not exist.")
        query = self.request.GET.get("q", "")
        vector = SearchVector("content")
        search_query = SearchQuery(query)
        object_list = (
            MessageModel.objects.filter(conversation_id=conv_id, content__icontains=query)
            .annotate(rank=SearchRank(vector, search_query), sub_content_count=Count("thoughtmodel")
            ).order_by("-rank")
        )

        context.update({
            "object_list": object_list,
            "has_search": True,
            "menu_title": "Messages",
            "prev_page": reverse("chat:conversations"),
        })
        return context

    def form_valid(self, form):
        form.instance.conversation_id = ConversationModel.objects.get(id=self.kwargs.get("id"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("chat:messages", kwargs={"id": self.kwargs.get("id")})


class ThoughtListView(CreateView):
    template_name = "thoughts.html"
    model = ThoughtModel
    fields = ["content", "date_time"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_search"] = False
        context["menu_title"] = "Thoughts"

        msg_id = self.kwargs.get("id")
        try:
            cur_msg_obj = MessageModel.objects.get(id=msg_id)
        except ConversationModel.DoesNotExist:
            raise Http404("Message does not exist.")
        object_list = ThoughtModel.objects.filter(message_id=msg_id)
        context["object_list"] = object_list
        context["prev_page"] = reverse("chat:messages", kwargs={"id": cur_msg_obj.conversation_id.id})
        context["message"] = cur_msg_obj
        return context

    def form_valid(self, form):
        form.instance.message_id = MessageModel.objects.get(id=self.kwargs.get("id"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("chat:thoughts", kwargs={"id": self.kwargs.get("id")})

src/chat/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Chat-app</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <body>
        {% include 'components/nav_bar.html' %}
        <div id="main-content">
            {% block content %}{% endblock %}
        </div>    
    </body>
</html>

src/chat/templates/components/chat_table.html
<div class="list-group">
    {% for obj in object_list %}
    <a href="{{ obj.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between"> 
            <h5 class="mb-1">{{ obj.content }}</h5>
            {% if obj.sub_content_count %}
            <span class="badge badge-primary badge-pill msg-count-bubble">{{ obj.sub_content_count }}</span>
            {% endif %}
        </div>
        {% if obj.description %}
        <p class="mb-1">{{ obj.description }}</p>
        {% endif %}
        <small>{{ obj.date_time }}</small>
    </a>
    {% endfor %}
</div>

src/chat/templates/components/nav_bar.html
<nav class="navbar navbar-dark bg-dark justify-content-between", id="nav-bar">
    <div>
        {% if prev_page %}
        <a class="navbar-brand" href="{{ prev_page }}">
            <svg id="nav-back" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" stroke-width="800" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
            </svg>
        </a>
        {% endif %}
    </div>
    <h1>{{ menu_title }}</h1>
    <div>
        {% if has_search %}
        <form action="{{ request.get_full_path }}" method="get" class="form-inline search-form">
            <input name="q" type="text" placeholder="Search..." class="form-control rounded mr-sm-2 search-input"/>
            <input class="btn btn-primary btn-md search-btn" type='submit' value='Search'/>
        </form>
        {% endif %}
    </div>
</nav>

src/chat/templates/components/text_entry_bar.html
{% load widget_tweaks %}

<div class="msg-bar">
    <form action='.' method='POST'>{% csrf_token %}
        <div class="input-group">
                {% render_field form.content class="form-control msg-content col-md-8" placeholder="Type here..." %}
                {% render_field form.date_time class="form-control msg-date-time col-md-4" %}
            <input class="btn btn-primary btn-lg msg-btn col-md-2" type='submit' value='Send'/>
        </div>
    </form>
</div>

src/chat/templates/conversation_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form action='.' method='POST'>{% csrf_token %}
    <div class="mb-3">
        <br>
        Title:
        {% render_field form.title class="form-control msg-content col-md-8" %}
        <br>
        Description:
        {% render_field form.description class="form-control" %}
        <br>
        Date:
        {% render_field form.date class="form-control msg-date-time col-md-8" %}
        <br>
        <input class="btn btn-primary btn-lg send-msg-btn" type='submit' value='Add new conversation'/>
    </div>
</form>

{% endblock %}

src/chat/templates/conversation_list.html
{% extends 'base.html' %}

{% block content %}

{% include 'components/chat_table.html' %}

<div>
    <a class="btn btn-secondary create-new-btn" href="{% url 'chat:create_conversation' %}">Create New</a>
</div>

{% endblock %}

src/chat/templates/messages.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-header bg-secondary text-light">{{ conversation.title }}</div>
    <div class="card-body card-description">
        <blockquote class="blockquote mb-0">
            <p>{{ conversation.description }}</p>
            <footer class="blockquote-footer">{{ conversation.date }}</footer>
        </blockquote>
    </div>
</div>
<br>

{% include 'components/chat_table.html' %}
{% include 'components/text_entry_bar.html' %}

{% endblock %}

src/chat/templates/thoughts.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-body card-description">
        <blockquote class="blockquote mb-0">
            <p>{{ message.content }}</p>
            <footer class="blockquote-footer">{{ message.date_time }}</footer>
        </blockquote>
    </div>
</div>
<br>

{% include 'components/chat_table.html' %}
{% include 'components/text_entry_bar.html' %}

{% endblock %}